### products
GET http://localhost:3000/product/products
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDRLeFluTjY3LlpOc1dsUm8zWXFtcGVTV05OVjZTNW13TWhpWTFxUFp6NllORllhM0pQbkMyIiwiaWQiOiI2NWZiMWUyZmVmNjYyMzM0ZmYzN2I0ZmUiLCJpYXQiOjE3MTA5NTYwNzksImV4cCI6MTcxMDk1OTY3OX0.dZy2LQ9XdUT9mb2uaGOg5RMjCFbsoyk-eVgNtkzoIeY

### products
GET http://localhost:3000/product/product/1
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDRLeFluTjY3LlpOc1dsUm8zWXFtcGVTV05OVjZTNW13TWhpWTFxUFp6NllORllhM0pQbkMyIiwiaWQiOiI2NWZiMWUyZmVmNjYyMzM0ZmYzN2I0ZmUiLCJpYXQiOjE3MTA5NTYwNzksImV4cCI6MTcxMDk1OTY3OX0.dZy2LQ9XdUT9mb2uaGOg5RMjCFbsoyk-eVgNtkzoIeY


### products
POST http://localhost:3000/product/create
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDRLeFluTjY3LlpOc1dsUm8zWXFtcGVTV05OVjZTNW13TWhpWTFxUFp6NllORllhM0pQbkMyIiwiaWQiOiI2NWZiMWUyZmVmNjYyMzM0ZmYzN2I0ZmUiLCJpYXQiOjE3MTA5NTYwNzksImV4cCI6MTcxMDk1OTY3OX0.dZy2LQ9XdUT9mb2uaGOg5RMjCFbsoyk-eVgNtkzoIeY

### products
PUT http://localhost:3000/product/update/1
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDRLeFluTjY3LlpOc1dsUm8zWXFtcGVTV05OVjZTNW13TWhpWTFxUFp6NllORllhM0pQbkMyIiwiaWQiOiI2NWZiMWUyZmVmNjYyMzM0ZmYzN2I0ZmUiLCJpYXQiOjE3MTA5NTYwNzksImV4cCI6MTcxMDk1OTY3OX0.dZy2LQ9XdUT9mb2uaGOg5RMjCFbsoyk-eVgNtkzoIeY

### products
DELETE  http://localhost:3000/product/del/1
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDRLeFluTjY3LlpOc1dsUm8zWXFtcGVTV05OVjZTNW13TWhpWTFxUFp6NllORllhM0pQbkMyIiwiaWQiOiI2NWZiMWUyZmVmNjYyMzM0ZmYzN2I0ZmUiLCJpYXQiOjE3MTA5NTYwNzksImV4cCI6MTcxMDk1OTY3OX0.dZy2LQ9XdUT9mb2uaGOg5RMjCFbsoyk-eVgNtkzoIeY